=== cdisc-org/DataExchange-ODM/archive/ODM1-1/odm_md_uc/odm1-1-0.dtd
<!--
  This is a generated file. Do not edit!
  Source file:   odm1-1-0.adtd
  Last modified: Fri Apr 26 16:53:36 EDT 2002
-->

<!--
The Clinical Data Interchange Standards Consortium has developed an
Operational Data Model for the storage and transfer of data and metadata
pertaining to clinical trials.  Version 1.1 of this model is available at 
http://www.cdisc.org/dtd/odm1-1-0.html.

The present DTD is derived from the above specification and expresses
certain syntactic constraints that all ODM documents must satisfy.  See the
above specification for further constraints, and for a definition of the
meaning of ODM documents.  This DTD is available at 
http://www.cdisc.org/dtd/odm1-1-0.dtd. 

The DTD is published in two forms: ODM1-1-0x.DTD includes 
parameterized entities to enable vendor extensions. ODM1-1-0.DTD has no
parameterized entities. As published, the two forms are functionally 
identical. ODM1-1-0x.DTD is designed to make it possible for a vendor to add 
elements and attributes, if they are needed, to more completely define
the metadata or data being transmitted.

Copyright (c) CDISC 2002
This document is the property of CDISC Inc. This document can be freely used
and reproduced without limitation as long as (1) it is not modified, and (2)
the entire copyright statement is included in the copy.  Modifications to
this document can only be made with written consent of CDISC Inc.
-->

<!ELEMENT ODM (Study*, AdminData*, ReferenceData*, ClinicalData*) >

<!ATTLIST ODM
          Description CDATA #IMPLIED
          FileType ( Snapshot | Transactional ) #REQUIRED
          Granularity (  All 
                     | Metadata 
		     | AdminData 
		     | ReferenceData 
		     | AllClinicalData
		     | SingleSite
		     | SingleSubject
   	            ) #IMPLIED
          Archival (Yes) #IMPLIED
          FileOID CDATA #REQUIRED
          CreationDateTime CDATA #REQUIRED
          PriorFileOID CDATA #IMPLIED
          AsOfDateTime CDATA #IMPLIED
          >

<!ELEMENT Study (GlobalVariables, BasicDefinitions, MetaDataVersion*) >

<!ATTLIST Study
          OID CDATA #REQUIRED
          >

<!ELEMENT GlobalVariables (StudyName, StudyDescription, ProtocolName) >

<!ELEMENT StudyName (#PCDATA) >

<!ELEMENT StudyDescription (#PCDATA) >

<!ELEMENT ProtocolName (#PCDATA) >

<!ELEMENT BasicDefinitions (MeasurementUnit*) >

<!ELEMENT MeasurementUnit (Symbol) >

<!ATTLIST MeasurementUnit
          OID CDATA #REQUIRED
          Name CDATA #REQUIRED
          >

<!ELEMENT Symbol (TranslatedText+) >

<!ELEMENT TranslatedText (#PCDATA) >

<!ATTLIST TranslatedText
          xml:lang CDATA #REQUIRED
          >

<!ELEMENT MetaDataVersion (Include?, Protocol?, StudyEventDef*, FormDef*,
			  ItemGroupDef*, ItemDef*, CodeList*,
			  Presentation*) >

<!ATTLIST MetaDataVersion
          OID CDATA #REQUIRED
          Name CDATA #REQUIRED
          >

<!ELEMENT Include EMPTY >

<!ATTLIST Include
          StudyOID CDATA #REQUIRED
          MetaDataVersionOID CDATA #REQUIRED
          >

<!ELEMENT Protocol (StudyEventRef+) >

<!ELEMENT StudyEventRef EMPTY >

<!ATTLIST StudyEventRef
          StudyEventOID CDATA #REQUIRED
          OrderNumber CDATA #IMPLIED
          Mandatory (Yes | No) #REQUIRED
          >

<!ELEMENT StudyEventDef (FormRef+) >

<!ATTLIST StudyEventDef
          OID CDATA #REQUIRED
          Name CDATA #REQUIRED
          Repeating (Yes | No) #REQUIRED
          Type (Scheduled | Unscheduled | Common) #REQUIRED
          Category CDATA #IMPLIED
          >

<!ELEMENT FormRef EMPTY >

<!ATTLIST FormRef
          FormOID CDATA #REQUIRED
          OrderNumber CDATA #IMPLIED
          Mandatory (Yes | No) #REQUIRED
          >

<!ELEMENT FormDef (ItemGroupRef+, ArchiveLayout*) >

<!ATTLIST FormDef
          OID CDATA #REQUIRED
          Name CDATA #REQUIRED
          Repeating (Yes | No) #REQUIRED
          >

<!ELEMENT ItemGroupRef EMPTY >

<!ATTLIST ItemGroupRef
          ItemGroupOID CDATA #REQUIRED
          OrderNumber CDATA #IMPLIED
          Mandatory (Yes | No) #REQUIRED
          >

<!ELEMENT ItemGroupDef (ItemRef+) >

<!ATTLIST ItemGroupDef
          OID CDATA #REQUIRED
          Name CDATA #REQUIRED
          Repeating (Yes | No) #REQUIRED
          IsReferenceData (Yes | No) #IMPLIED
          SASDatasetName CDATA #IMPLIED
          Domain CDATA #IMPLIED
          Origin CDATA #IMPLIED
          Role CDATA #IMPLIED
          Comment CDATA #IMPLIED
          >

<!ELEMENT ItemRef EMPTY >

<!ATTLIST ItemRef
          ItemOID CDATA #REQUIRED
          OrderNumber CDATA #IMPLIED
          Mandatory (Yes | No) #REQUIRED
          >

<!ELEMENT ItemDef (Question?, ExternalQuestion?, MeasurementUnitRef*,
                  RangeCheck*, CodeListRef?, Role*) >

<!ATTLIST ItemDef
          OID CDATA #REQUIRED
          Name CDATA #REQUIRED
          DataType (integer | float | date | datetime | time | 
                  text) #REQUIRED
          Length CDATA #IMPLIED
          SignificantDigits CDATA #IMPLIED
          SASFieldName CDATA #IMPLIED
          SDSVarName CDATA #IMPLIED
          Origin CDATA #IMPLIED
          Comment CDATA #IMPLIED
          >

<!ELEMENT Question (TranslatedText+) >

<!ELEMENT ExternalQuestion EMPTY >

<!ATTLIST ExternalQuestion
          Dictionary CDATA #IMPLIED
          Version CDATA #IMPLIED
          Code CDATA #IMPLIED
          >

<!ELEMENT MeasurementUnitRef EMPTY >

<!ATTLIST MeasurementUnitRef
          MeasurementUnitOID CDATA #REQUIRED
          >

<!ELEMENT RangeCheck (CheckValue+, MeasurementUnitRef?, ErrorMessage?) >

<!ATTLIST RangeCheck
          Comparator (LT | LE | GT | GE | EQ | NE | IN | NOTIN) #REQUIRED
          SoftHard (Soft | Hard) #REQUIRED
          >

<!ELEMENT CheckValue (#PCDATA) >

<!ELEMENT ErrorMessage (TranslatedText+) >

<!ELEMENT CodeListRef EMPTY >

<!ATTLIST CodeListRef
          CodeListOID CDATA #REQUIRED
          >

<!ELEMENT Role (#PCDATA) >

<!ELEMENT CodeList (CodeListItem* | ExternalCodeList) >

<!ATTLIST CodeList
          OID CDATA #REQUIRED
          Name CDATA #REQUIRED
          DataType (integer | float | text) #REQUIRED
          SASFormatName CDATA #IMPLIED
          >

<!ELEMENT CodeListItem (Decode) >

<!ATTLIST CodeListItem
          CodedValue CDATA #REQUIRED
          >

<!ELEMENT Decode (TranslatedText+) >

<!ELEMENT ExternalCodeList EMPTY >

<!ATTLIST ExternalCodeList
          Dictionary CDATA #IMPLIED
          Version CDATA #IMPLIED
          >

<!ELEMENT ArchiveLayout EMPTY >

<!ATTLIST ArchiveLayout
          OID CDATA #REQUIRED
          PdfFileName CDATA #REQUIRED
          PresentationOID CDATA #IMPLIED
          >

<!ELEMENT Presentation (#PCDATA) >

<!ATTLIST Presentation
          OID CDATA #REQUIRED
          xml:lang CDATA #IMPLIED
          >

<!ELEMENT AdminData (User*, Location*, SignatureDef*) >

<!ATTLIST AdminData
          StudyOID CDATA #IMPLIED
          >

<!ELEMENT User (LoginName?, DisplayName?, FullName?, FirstName?, LastName?,
               Organization?, Address*, Email*, Picture?, Pager?, Fax*, Phone*,
               LocationRef*, Certificate*) >

<!ATTLIST User
          OID CDATA #REQUIRED
          UserType (Sponsor | Investigator | Lab | Other) #IMPLIED
          >

<!ELEMENT LoginName (#PCDATA) >

<!ELEMENT DisplayName (#PCDATA) >

<!ELEMENT FullName (#PCDATA) >

<!ELEMENT FirstName (#PCDATA) >

<!ELEMENT LastName (#PCDATA) >

<!ELEMENT Organization (#PCDATA) >

<!ELEMENT Address (StreetName*, City?, StateProv?, Country?, PostalCode?,
                  OtherText?) >

<!ELEMENT StreetName (#PCDATA) >

<!ELEMENT City (#PCDATA) >

<!ELEMENT StateProv (#PCDATA) >

<!ELEMENT Country (#PCDATA) >

<!ELEMENT PostalCode (#PCDATA) >

<!ELEMENT OtherText (#PCDATA) >

<!ELEMENT Email (#PCDATA) >

<!ELEMENT Picture EMPTY >

<!ATTLIST Picture
          PictureFileName CDATA #REQUIRED
          ImageType CDATA #IMPLIED
          >

<!ELEMENT Pager (#PCDATA) >

<!ELEMENT Fax (#PCDATA) >

<!ELEMENT Phone (#PCDATA) >

<!ELEMENT LocationRef EMPTY >

<!ATTLIST LocationRef
          LocationOID CDATA #REQUIRED
          >

<!ELEMENT Certificate (#PCDATA) >

<!ELEMENT Location (MetaDataVersionRef+) >

<!ATTLIST Location
          OID CDATA #REQUIRED
          Name CDATA #REQUIRED
          LocationType (Sponsor | Site | CRO | Lab | Other) #IMPLIED
          >

<!ELEMENT MetaDataVersionRef EMPTY >

<!ATTLIST MetaDataVersionRef
          StudyOID CDATA #REQUIRED
          MetaDataVersionOID CDATA #REQUIRED
          EffectiveDate CDATA #REQUIRED
          >

<!ELEMENT SignatureDef (Meaning, LegalReason) >

<!ATTLIST SignatureDef
          OID CDATA #REQUIRED
          Methodology (Digital | Electronic) #IMPLIED
          >

<!ELEMENT Meaning (#PCDATA) >

<!ELEMENT LegalReason (#PCDATA) >

<!ELEMENT ReferenceData (ItemGroupData*) >

<!ATTLIST ReferenceData
          StudyOID CDATA #REQUIRED
          MetaDataVersionOID CDATA #REQUIRED
          >

<!ELEMENT ClinicalData (SubjectData*) >

<!ATTLIST ClinicalData
          StudyOID CDATA #REQUIRED
          MetaDataVersionOID CDATA #REQUIRED
          >

<!ELEMENT SubjectData (AuditRecord?,Signature?, InvestigatorRef?, SiteRef?,
		      Annotation*,StudyEventData*) >

<!ATTLIST SubjectData
          SubjectKey CDATA #REQUIRED
          TransactionType (Insert | Update | Remove | Upsert | Context) #IMPLIED
          >

<!ELEMENT StudyEventData (AuditRecord?,Signature?,Annotation*,FormData* ) >

<!ATTLIST StudyEventData
          StudyEventOID CDATA #REQUIRED
          StudyEventRepeatKey CDATA #IMPLIED
          TransactionType (Insert | Update | Remove | Upsert | Context) #IMPLIED
          >

<!ELEMENT FormData (AuditRecord?, Signature?, ArchiveLayoutRef?, 
				Annotation*,ItemGroupData* ) >

<!ATTLIST FormData
          FormOID CDATA #REQUIRED
          FormRepeatKey CDATA #IMPLIED
          TransactionType (Insert | Update | Remove | Upsert | Context) #IMPLIED
          >

<!ELEMENT ArchiveLayoutRef EMPTY >

<!ATTLIST ArchiveLayoutRef
          ArchiveLayoutOID CDATA #REQUIRED
          >

<!ELEMENT ItemGroupData (AuditRecord?,Signature?,Annotation*,ItemData* ) >

<!ATTLIST ItemGroupData
          ItemGroupOID CDATA #REQUIRED
          ItemGroupRepeatKey CDATA #IMPLIED
          TransactionType (Insert | Update | Remove | Upsert | Context) #IMPLIED
          >

<!ELEMENT ItemData (AuditRecord?,Signature?, MeasurementUnitRef?,
		   Annotation* ) >

<!ATTLIST ItemData
          ItemOID CDATA #REQUIRED
          TransactionType (Insert | Update | Remove | Upsert | Context) #IMPLIED
          Value CDATA #IMPLIED
          IsNull (Yes) #IMPLIED
          >

<!ELEMENT Annotation (Comment?, Flag*) >

<!ATTLIST Annotation
          SeqNum CDATA #REQUIRED
          TransactionType (Insert | Update | Remove | Upsert | Context) #IMPLIED
          >

<!ELEMENT Comment (#PCDATA) >

<!ATTLIST Comment
          SponsorOrSite (Sponsor | Site) #IMPLIED
          >

<!ELEMENT Flag (FlagValue, FlagType?) >

<!ELEMENT FlagValue (#PCDATA) >

<!ATTLIST FlagValue
          CodeListOID CDATA #REQUIRED
          >

<!ELEMENT FlagType (#PCDATA) >

<!ATTLIST FlagType
          CodeListOID CDATA #REQUIRED
          >

<!ELEMENT Signature (UserRef, LocationRef, SignatureRef, DateTimeStamp,
                    CryptoBindingManifest?) >

<!ELEMENT UserRef EMPTY >

<!ATTLIST UserRef
          UserOID CDATA #REQUIRED
          >

<!ELEMENT SignatureRef EMPTY >

<!ATTLIST SignatureRef
          SignatureOID CDATA #REQUIRED
          >

<!ELEMENT DateTimeStamp (#PCDATA) >

<!ELEMENT CryptoBindingManifest (#PCDATA) >

<!ELEMENT AuditRecord (UserRef, LocationRef, DateTimeStamp, ReasonForChange?,
                      SourceID?) >

<!ELEMENT ReasonForChange (#PCDATA) >

<!ELEMENT SourceID (#PCDATA) >

<!ELEMENT InvestigatorRef EMPTY >

<!ATTLIST InvestigatorRef
          UserOID CDATA #REQUIRED
          >

<!ELEMENT SiteRef EMPTY >

<!ATTLIST SiteRef
          LocationOID CDATA #REQUIRED
          >

=== cdisc-org/DataExchange-ODM/archive/ODM1-1/odm1_1_0_example.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE ODM SYSTEM "odm1-1-0.dtd" >
<!--
	This XML Example is intended to provide a very small, valid example of 
	a CDISC study using CDISC ODM V1.1
-->
<!--
	In this small example study, a pharmaceutical company is conducting a 
	Phase II initial efficacy study.  This pharmaceutical company 
	("The Pharm") has hired a contract research organization (CRO) to
 	collect, clean and complete data for this study.  The Pharm and the CRO 
	use completely different clinical data management systems, so the 2 
	companies have agreed to use CDISC'S ODM V1.1 for their data exchange.

	The data are coming in slowly and only the CRF pages from the first two
	visits for two patients have been returned from the investigational site
	to the CRO so far.  During the first visit, both demographic and vital 
	statistics data are collected. During the second visit, only vital 
	statistics are collected.  The data from the first patient's first visit
	included an incorrect systolic blood pressure. The incorrect value was 
	changed to the correct value in a separate data entry session, and this 
	change was captured in the audit trail of the clinical data management 
	system. 
-->
<ODM FileType="Transactional" FileOID="987-654-321" CreationDateTime="2001-11-15T16:37:21-05:00" AsOfDateTime="2001-11-15T16:37:21-05:00" Description="Two visits for patients P001 and P027, plus updates of data for P001" Granularity="All">
  <Study OID="123-456-789">
    <GlobalVariables>
      <StudyName>HarrisonA</StudyName>
      <StudyDescription>Phase II initial efficacy</StudyDescription>
      <ProtocolName>B00-2136</ProtocolName>
    </GlobalVariables>
    <BasicDefinitions/>
    <!-- Beginning of metadata definitions . . .    -->
    <MetaDataVersion OID="MetaDataVersion.001" Name="Release 1">
      <Protocol>
        <!--There are 2 study events defined, corresponding to Visit 1 and Visit 2.  On "Demog and Vitials:, signing unit is used, while on Visit 2, the "Vitals Only" is used
 -->
        <StudyEventRef StudyEventOID="VISIT_1" Mandatory="Yes"/>
        <StudyEventRef StudyEventOID="VISIT_2" Mandatory="Yes"/>
      </Protocol>
      <StudyEventDef OID="VISIT_1" Name="Visit1" Repeating="No" Type="Scheduled">
        <FormRef FormOID="PAGE_1" Mandatory="No"/>
      </StudyEventDef>
      <StudyEventDef OID="VISIT_2" Name="Visit2" Repeating="No" Type="Scheduled">
        <FormRef FormOID="PAGE_2" Mandatory="No"/>
      </StudyEventDef>
      <!--There are 2 signing units defined: one to collect demographics AND vitals and one to collect just vitals.
-->
      <FormDef OID="PAGE_1" Name="Demog and Vitals" Repeating="No">
        <ItemGroupRef ItemGroupOID="DEMOG" Mandatory="No"/>
        <ItemGroupRef ItemGroupOID="VITALS" Mandatory="No"/>
      </FormDef>
      <FormDef OID="PAGE_2" Name="Vitals Only" Repeating="No">
        <ItemGroupRef ItemGroupOID="VITALS" Mandatory="No"/>
      </FormDef>
      <!--There are 2 item groups (ItemGroups): Demographics and Vitals
-->
      <!--The demographics item group contains 7 item references (ItemRef) corresponding to Patient ID, Patient Initials, Sex, Date of Birth, Sponsor Patient ID, Weight (lb) and Weight (kg)-->
      <ItemGroupDef OID="DEMOG" Name="Demographics" Repeating="Yes" IsReferenceData="No" SASDatasetName="DEMOG">
        <ItemRef ItemOID="PT" Mandatory="No"/>
        <ItemRef ItemOID="INITIALS" Mandatory="No"/>
        <ItemRef ItemOID="SEX" Mandatory="No"/>
        <ItemRef ItemOID="DOB" Mandatory="No"/>
        <ItemRef ItemOID="SPONSOR_PTID" Mandatory="No"/>
        <ItemRef ItemOID="WEIGHT_LB" Mandatory="No"/>
        <ItemRef ItemOID="WEIGHT_KG" Mandatory="No"/>
      </ItemGroupDef>
      <!--The Vitals item group contains 6 item references (ItemRef) corresponding to the Patient ID, Visit Name, Systolic Blood Pressure, Diastolic Blood Pressure, Sponsor Patient ID, and Occurrence Number (of repeat measurement).-->
      <ItemGroupDef OID="VITALS" Name="Vital Signs" Repeating="Yes" IsReferenceData="No" SASDatasetName="VITALS">
        <ItemRef ItemOID="PT" Mandatory="No"/>
        <ItemRef ItemOID="VISITNAME" Mandatory="No"/>
        <ItemRef ItemOID="SBP" Mandatory="No"/>
        <ItemRef ItemOID="DBP" Mandatory="No"/>
        <ItemRef ItemOID="SPONSOR_PTID" Mandatory="No"/>
        <ItemRef ItemOID="OCCUR_NUM" Mandatory="No"/>
      </ItemGroupDef>
      <!--There are 12 items defined: Patient ID, Initials, Date of Birth, Sex, Systolic Blood Pressure, Diastolic Blood Pressure, Visit Name, Sponsor Patient ID, Visit Number (not currently used), Occurrence NUmber, Weight (lb) and Weight (kg).-->
      <ItemDef OID="PT" Name="PT" DataType="text" Length="4" SASFieldName="PT"/>
      <ItemDef OID="INITIALS" Name="Initials" DataType="text" Length="5" SASFieldName="INITIALS"/>
      <ItemDef OID="DOB" Name="Date of Birth" DataType="date" SASFieldName="DOB"/>
      <ItemDef OID="SEX" Name="Sex" DataType="text" Length="1" SASFieldName="SEX">
        <CodeListRef CodeListOID="CodeList.001"/>
      </ItemDef>
      <ItemDef OID="SBP" Name="Systolic Blood Pressure" DataType="integer" SASFieldName="SBP" Length="3"/>
      <ItemDef OID="DBP" Name="Diastolic Blood Pressure" DataType="integer" SASFieldName="DBP" Length="3"/>
      <ItemDef OID="VISITNAME" Name="Visit" DataType="text" Length="20" SASFieldName="VISNAME"/>
      <ItemDef OID="SPONSOR_PTID" Name="Sponsor Patient ID" DataType="text" Length="12" SASFieldName="SPONPTID"/>
      <ItemDef OID="VISITNUM" Name="Numeric Version of Visit" DataType="integer" SASFieldName="VISITNUM" Length="2"/>
      <ItemDef OID="OCCUR_NUM" Name="Occurence Number" DataType="integer" SASFieldName="OCCURNUM" Length="2"/>
      <ItemDef OID="WEIGHT_LB" Name="Weight in pounds" DataType="float" SASFieldName="WEIGHTLB" Length="4" SignificantDigits="1"/>
      <ItemDef OID="WEIGHT_KG" Name="Weight in kilograms " DataType="float" SASFieldName="WEIGHTKG" Length="4" SignificantDigits="1"/>
      <!--There is a single codelist for Sex with entries for "m" and "f".-->
      <CodeList OID="CodeList.001" Name="Sex" DataType="text" SASFormatName="CLSEX">
        <CodeListItem CodedValue="m">
          <Decode>
            <TranslatedText xml:lang="en">Male</TranslatedText>
          </Decode>
        </CodeListItem>
        <CodeListItem CodedValue="f">
          <Decode>
            <TranslatedText xml:lang="en">Female</TranslatedText>
          </Decode>
        </CodeListItem>
      </CodeList>
      <!--Since structure and content of Presentation have not yet been defined, we have inserted an empty Presentation element.-->
      <Presentation OID=""/>
    </MetaDataVersion>
  </Study>
  <!--Beginning of Administrative Data-->
  <AdminData>
    <!--There are 2 users: John Doe (the investigator) and Mary Brown (the data entry person)-->
    <User OID="User.001">
      <FirstName>John</FirstName>
      <LastName>Doe</LastName>
    </User>
    <User OID="User.002">
      <FirstName>Mary</FirstName>
      <LastName>Brown</LastName>
    </User>
    <!--There is 1 location: General Hospital (a site).-->
    <Location OID="Location.001" Name="General Hospital" LocationType="Site">
      <MetaDataVersionRef StudyOID="123-456-789" MetaDataVersionOID="MetaDataVersion.001" EffectiveDate="2001-10-19T10:45:57-05:00"/>
    </Location>
    <!--There is one signature definition (electronic signature for data entry)
-->
    <SignatureDef OID="SignatureDef.001" Methodology="Electronic">
      <Meaning>Entry</Meaning>
      <LegalReason>Signer accepts responsibility for initial data entry</LegalReason>
    </SignatureDef>
  </AdminData>
  <!--Beginning of Clinical Data-->
  <ClinicalData StudyOID="123-456-789" MetaDataVersionOID="MetaDataVersion.001">
    <!-- SubjectData element for the first of 2 patients in this example  -->
    <SubjectData SubjectKey="P001" TransactionType="Insert">
      <!--  EventData element for Visit 1 for this patient  -->
      <StudyEventData StudyEventOID="VISIT_1">
        <!-- FormData element for the DEMOG and Vitals form collected on Visit 1 (Original)  -->
        <FormData FormOID="PAGE_1">
          <AuditRecord>
            <UserRef UserOID="User.002"/>
            <LocationRef LocationOID="Location.001"/>
            <DateTimeStamp>2001-05-31-T10:08:40-05:00</DateTimeStamp>
          </AuditRecord>
          <!--  Electronic signature for this form   -->
          <Signature>
            <UserRef UserOID="User.001"/>
            <LocationRef LocationOID="Location.001"/>
            <SignatureRef SignatureOID="SignatureDef.001"/>
            <DateTimeStamp>2001-05-30T10:06:32-05:00</DateTimeStamp>
          </Signature>
          <!--  ItemGroupData element for the Demographics part of the form   -->
          <ItemGroupData ItemGroupOID="DEMOG" ItemGroupRepeatKey="1">
            <ItemData ItemOID="PT" Value="P001"/>
            <ItemData ItemOID="INITIALS" Value="AMH"/>
            <ItemData ItemOID="SEX" Value="f"/>
            <ItemData ItemOID="DOB" Value="1947-07-16"/>
            <ItemData ItemOID="SPONSOR_PTID" Value="B00-2136-001"/>
            <ItemData ItemOID="WEIGHT_LB" Value="150"/>
            <ItemData ItemOID="WEIGHT_KG" Value="68.18"/>
            <!--  ItemGroupData element for the Vitals part of the form     -->
          </ItemGroupData>
          <ItemGroupData ItemGroupOID="VITALS" ItemGroupRepeatKey="">
            <ItemData ItemOID="PT" Value="P001"/>
            <ItemData ItemOID="VISITNAME" Value="Visit1"/>
            <ItemData ItemOID="SBP" Value="120"/>
            <ItemData ItemOID="DBP" Value="80"/>
            <ItemData ItemOID="SPONSOR_PTID" Value="B00-2136-001"/>
            <ItemData ItemOID="OCCUR_NUM" Value="1"/>
          </ItemGroupData>
        </FormData>
        <!--  FormData element for the Vitals form collected on Visit 1 (Modified)    -->
      </StudyEventData>
      <!-- StudyEventData element for Visit 2 for the patient  -->
